import test from 'node:test';
import assert from 'node:assert/strict';
import { DATA_STORAGE_KEY, LocalStorageRepository } from '../dist/data/repository.js';
import { SigmaService } from '../dist/domain/service.js';
const store=raw=>{const values=new Map([[DATA_STORAGE_KEY,JSON.stringify(raw)]]);return{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,String(v)),removeItem:k=>values.delete(k)}};
const profile=(id,type='independent',extra={})=>({id,displayName:id.toUpperCase(),profileType:type,createdAt:'x',updatedAt:'x',...extra});
const base=()=>({schemaVersion:2,activeProfileId:'a',activeActorProfileId:'a',profiles:[profile('a'),profile('b'),profile('c'),profile('m','managed',{managedKind:'child',managedByProfileIds:['a']}),profile('n','managed',{managedKind:'dependant',managedByProfileIds:['a']})],measurements:[],standardSizes:[],brandFits:[],families:[{id:'f',name:'Home',createdByProfileId:'a',createdAt:'x',updatedAt:'x'}],familyMemberships:[{id:'fa',familyId:'f',profileId:'a',addedByProfileId:'a',createdAt:'x'},{id:'fm',familyId:'f',profileId:'m',addedByProfileId:'a',createdAt:'x'}],adultConnections:[],sharingGrants:[]});
const grant=(extra={})=>({id:'g',ownerProfileId:'a',recipientProfileId:'b',grantedByProfileId:'a',scope:{type:'profile'},status:'active',grantedAt:'x',...extra});
const connection=(status,extra={})=>({id:'c1',initiatorProfileId:'a',recipientProfileId:'b',status,requestedAt:'x',...extra});
const status=data=>new LocalStorageRepository(store(data)).load().status;

test('schema 2 rejects impossible grant and manager authority',()=>{const cases=[];let d=base();d.sharingGrants=[grant({grantedByProfileId:'c'})];cases.push(d);d=base();d.sharingGrants=[grant({ownerProfileId:'m',grantedByProfileId:'b'})];cases.push(d);d=base();d.sharingGrants=[grant({ownerProfileId:'m',recipientProfileId:'b',grantedByProfileId:'a'})];cases.push(d);d=base();d.profiles.find(p=>p.id==='m').managedByProfileIds=['n'];cases.push(d);for(const value of cases)assert.equal(status(value),'corrupt');});

test('schema 2 validates revocation metadata and authority',()=>{const variants=[grant({status:'revoked',revokedByProfileId:'a'}),grant({status:'revoked',revokedAt:'x'}),grant({status:'revoked',revokedAt:'x',revokedByProfileId:'missing'}),grant({status:'revoked',revokedAt:'x',revokedByProfileId:'c'})];for(const g of variants){const d=base();d.sharingGrants=[g];assert.equal(status(d),'corrupt');}const valid=base();valid.sharingGrants=[grant({status:'revoked',revokedAt:'x',revokedByProfileId:'a'})];assert.equal(status(valid),'ok');});

test('schema 2 enforces connection lifecycle metadata and participant disconnection',()=>{const invalid=[connection('disconnected',{respondedAt:'x',disconnectedByProfileId:'a'}),connection('disconnected',{respondedAt:'x',disconnectedAt:'x'}),connection('disconnected',{respondedAt:'x',disconnectedAt:'x',disconnectedByProfileId:'c'}),connection('active'),connection('active',{respondedAt:'x',disconnectedAt:'x'}),connection('declined'),connection('pending',{respondedAt:'x'})];for(const c of invalid){const d=base();d.adultConnections=[c];assert.equal(status(d),'corrupt');}for(const c of [connection('pending'),connection('active',{respondedAt:'x'}),connection('declined',{respondedAt:'x'}),connection('disconnected',{respondedAt:'x',disconnectedAt:'x',disconnectedByProfileId:'b'})]){const d=base();d.adultConnections=[c];assert.equal(status(d),'ok');}});

test('authority-corrupt raw storage is preserved and remains mutation-blocked',()=>{const d=base();d.sharingGrants=[grant({grantedByProfileId:'c'})];const local=store(d);const raw=local.getItem(DATA_STORAGE_KEY);const service=new SigmaService(new LocalStorageRepository(local));assert.equal(service.storageStatus().status,'corrupt');assert.throws(()=>service.createProfile({displayName:'New',profileType:'independent'}),/must be reset/);assert.equal(local.getItem(DATA_STORAGE_KEY),raw);});
