export type GuidanceTool = 'soft_tape'|'rigid_ruler'|'stadiometer'|'scales'|'calipers'|'foot_measuring_device'|'ring_sizer'|'other';
export type GuidanceAssistance = 'self'|'assisted'|'either'|'professional_preferred';
export type GuidanceView = 'front'|'back'|'side'|'top'|'detail'|'not_defined';
export interface MeasurementGuidance {
  summary:string; location:string; method:readonly string[]; preparation?:readonly string[]; commonErrors?:readonly string[];
  tool:GuidanceTool; assistance:GuidanceAssistance; posture?:string; clothing?:string;
  illustration?:{anatomyAnchor:string;view:GuidanceView;status:'placeholder'|'approved';assetId?:string};
  futureTutorialKey?:string;
}
type Seed={location:string;method:readonly string[];tool?:GuidanceTool;assistance?:GuidanceAssistance;posture?:string;clothing?:string;preparation?:readonly string[];errors?:readonly string[];anchor:string;view?:GuidanceView;summary?:string};
const tape=(location:string,method:readonly string[],anchor:string,extra:Partial<Seed>={}):Seed=>({location,method,anchor,tool:'soft_tape',assistance:'either',posture:'Stand naturally and breathe normally unless the steps say otherwise.',clothing:'Measure over bare skin or thin, close-fitting clothing.',errors:['Twisting, tilting or pulling the tape tight enough to compress the body.'],...extra});
const seeds:Record<string,Seed>={
 'measurement.height':{location:'From the level floor to the highest point of the head.',method:['Stand with heels on a level floor and the back of the head in a natural position.','Look straight ahead and lower a flat headpiece to touch the crown.','Read the vertical height without shoes.'],tool:'stadiometer',assistance:'assisted',posture:'Stand upright, feet flat and weight evenly distributed.',clothing:'Remove shoes and bulky hair accessories.',errors:['Measuring in shoes, looking up or down, or measuring against a sloping floor.'],anchor:'Body',view:'side'},
 'measurement.weight':{location:'Whole-body mass measured through the feet on a level set of scales.',method:['Place the scales on a hard, level surface.','Step onto the centre and keep still until the reading settles.','Record the displayed value and unit.'],tool:'scales',assistance:'self',posture:'Stand centred and still.',clothing:'Use a consistent clothing condition when comparing entries.',errors:['Using carpet, leaning on support, or comparing readings taken under very different conditions.'],anchor:'Body',view:'front'},
 'measurement.head-circumference':tape('Around the widest part of the head, above the eyebrows and ears and across the fullest point at the back.',['Place the tape just above the eyebrows and ears.','Pass it level around the fullest point at the back of the head.','Record the snug circumference without compressing hair or skin.'],'Body > Head and neck',{posture:'Keep the head level and look forward.',clothing:'Remove hats and bulky hair accessories.',errors:['Letting the tape rise at the back or measuring over bulky hair.'],view:'side'}),
 'measurement.neck-circumference':tape('Around the base of the neck at the level where a close collar would sit, below the larynx.',['Wrap the tape around the base of the neck and keep it level.','Keep the tape in contact without tightening it.','Record after a normal breath; this anatomical circumference is not automatically a garment collar size.'],'Body > Head and neck',{posture:'Look forward with shoulders relaxed.',errors:['Measuring high under the jaw, pulling tight, or substituting a labelled collar size.'],view:'front'}),
 'measurement.chest-circumference':tape('Around the torso at the fullest part of the chest, under the armpits and across the shoulder blades.',['Pass the tape under the arms around the fullest chest level.','Check that it is horizontal across the back.','Relax the arms and record after a normal exhale.'],'Body > Torso',{assistance:'assisted',errors:['Lifting the arms, expanding the chest deliberately, or placing the tape at bust or underbust level.'],view:'front'}),
 'measurement.bust-circumference':tape('Around the fullest projection of the bust and level across the back.',['Pass the tape around the fullest bust point.','Check the tape is horizontal and not cutting into the body.','Lower the arms and record after a normal breath.'],'Body > Torso',{assistance:'assisted',clothing:'Wear the undergarment normally used for the intended record, or note that none was worn.',errors:['Using the underbust line, flattening the bust, or allowing the back tape to rise.'],view:'front'}),
 'measurement.underbust-circumference':tape('Around the ribcage immediately beneath the bust fold, level across the back.',['Place the tape directly beneath the bust.','Keep it horizontal and snug without compressing.','Record after a normal exhale.'],'Body > Torso',{assistance:'either',errors:['Measuring across the bust, dropping below the ribcage, or adding ease for a garment.'],view:'front'}),
 'measurement.waist-circumference':tape('At the midpoint between the lowest palpable rib and the top of the hip bone, around the torso.', ['Locate the lowest rib and the top of the hip bone on each side.','Place the tape at the midpoint between those landmarks and keep it horizontal.','Stand naturally and record after a normal exhale without tightening the tape.'],'Body > Torso',{preparation:['This Sigma method is anatomical: it is not the trouser waistband, navel, visually narrowest point, or a high/low clothing waist.'],errors:['Substituting a clothing waist position, holding the breath, or compressing the abdomen.'],view:'front'}),
 'measurement.hip-circumference':tape('Around the fullest part of the hips and buttocks.', ['Wrap the tape around the widest combined hip and buttock level.','Check from the side that the tape is horizontal.','Stand with feet together and record without compressing.'],'Body > Torso',{assistance:'assisted',posture:'Stand upright with feet together and weight even.',errors:['Measuring only across the hip bones or letting the tape slope over the buttocks.'],view:'side'}),
 'measurement.shoulder-width':{location:'Across the back from one shoulder tip (acromion) to the other.',method:['Identify the bony tip at each outer shoulder.','Measure across the natural curve of the upper back between those points.','Keep shoulders relaxed and record the distance.'],tool:'soft_tape',assistance:'assisted',posture:'Stand naturally with arms relaxed.',clothing:'Use bare shoulders or thin clothing.',errors:['Measuring straight through the body, including upper-arm width, or lifting the shoulders.'],anchor:'Body > Torso',view:'back'},
 'measurement.back-width':{location:'Across the upper back between the rear folds where the arms meet the torso.',method:['Locate the rear crease of each armpit with arms relaxed.','Measure horizontally across the back between the creases.','Keep the tape following the surface without adding garment ease.'],tool:'soft_tape',assistance:'assisted',posture:'Stand upright with arms resting naturally.',errors:['Using shoulder-tip width, rounding the shoulders, or measuring around the torso.'],anchor:'Body > Torso',view:'back'},
 'measurement.torso-length':{location:'Along the back from the prominent bone at the base of the neck to the natural waist level.',method:['Locate the prominent neck-base vertebra and the Sigma anatomical waist level.','Run the tape down the centre back following the body contour.','Record the distance while standing naturally.'],tool:'soft_tape',assistance:'assisted',posture:'Stand upright with the head level.',errors:['Using a garment hem, measuring to the waistband, or holding the tape straight away from the back.'],anchor:'Body > Torso',view:'back'},
 'measurement.arm-length':{location:'From the shoulder tip to the wrist bone along the outside of the arm.',method:['Locate the outer shoulder tip and the wrist bone.','Bend the elbow slightly and run the tape over the elbow along the outside arm.','Record at the wrist bone.'],tool:'soft_tape',assistance:'assisted',posture:'Keep the arm relaxed with a slight elbow bend.',errors:['Measuring with a locked elbow, starting at the neck, or stopping at a sleeve cuff.'],anchor:'Body > Upper limbs',view:'side'},
 'measurement.sleeve-length':{location:'From the centre back neck, across the shoulder and bent elbow, to the wrist bone.',method:['Place the tape at the centre back neck base.','Run it over the shoulder tip and along the outside of a slightly bent arm.','Record at the wrist bone.'],tool:'soft_tape',assistance:'assisted',posture:'Stand naturally with the elbow slightly bent.',errors:['Confusing this with shoulder-to-wrist arm length or measuring a garment sleeve.'],anchor:'Body > Upper limbs',view:'back'},
 'measurement.upper-arm-circumference':tape('Around the fullest part of the upper arm between shoulder and elbow.',['Let the arm hang relaxed.','Wrap the tape around the fullest upper-arm level, perpendicular to the arm.','Record without flexing or compressing.'],'Body > Upper limbs',{errors:['Flexing the muscle, tilting the tape, or measuring too close to the armpit.'],view:'detail'}),
 'measurement.forearm-circumference':tape('Around the fullest part of the forearm below the elbow.',['Let the arm and hand relax.','Wrap the tape around the fullest forearm level.','Keep it perpendicular to the arm and record without compression.'],'Body > Upper limbs',{errors:['Clenching the hand, measuring over the elbow, or angling the tape.'],view:'detail'}),
 'measurement.wrist-circumference':tape('Around the wrist at the narrowest point just beyond the wrist bones.',['Relax the hand.','Wrap the tape around the narrow wrist point adjacent to the wrist bones.','Record with the tape touching but not tightening.'],'Body > Upper limbs > Hand',{posture:'Keep the hand in line with the forearm.',errors:['Measuring over a watch, using the wider hand joint, or adding strap allowance.'],view:'detail'}),
 'measurement.hand-length':{location:'From the centre wrist crease to the tip of the longest finger.',method:['Place the hand flat with fingers together and relaxed.','Align a rigid ruler with the centre wrist crease.','Measure to the longest fingertip.'],tool:'rigid_ruler',assistance:'self',posture:'Hand flat, palm up or down, without stretching the fingers.',errors:['Starting at the heel of the palm, measuring only to the middle finger when another is longer, or bending the wrist.'],anchor:'Body > Upper limbs > Hand',view:'top'},
 'measurement.hand-width':{location:'Straight across the widest part of the palm below the finger joints, excluding the thumb.',method:['Place the hand flat with fingers together.','Measure across the widest palm points below the knuckles.','Exclude the thumb from the width.'],tool:'rigid_ruler',assistance:'self',posture:'Hand flat and relaxed.',errors:['Including the thumb, spreading the fingers, or measuring diagonally.'],anchor:'Body > Upper limbs > Hand',view:'top'},
 'measurement.palm-circumference':tape('Around the widest part of the palm across the knuckles, excluding the thumb.',['Hold the hand relaxed with fingers together.','Wrap the tape around the knuckles and palm without including the thumb.','Record the circumference without clenching.'],'Body > Upper limbs > Hand',{errors:['Including the thumb, making a fist, or placing the tape around the wrist.'],view:'detail'}),
 'measurement.finger-circumference':tape('Around the intended finger at the position where a ring would rest, while accounting for the widest knuckle it must pass.', ['Measure the finger at the intended wearing position.','Also check the widest knuckle if it is larger.','Record the anatomical circumference and location; this does not select or recommend a Ring size.'],'Body > Upper limbs > Hand > Fingers',{tool:'soft_tape',preparation:['Measure the intended finger and hand; finger size can vary between them.'],errors:['Pulling the tape tight, measuring a different finger, or treating this record as a regional ring size.'],view:'detail'}),
 'measurement.inseam':{location:'From the crotch junction down the inside leg to the floor or chosen anatomical ankle endpoint.',method:['Stand upright with feet slightly apart.','Place the tape firmly at the crotch junction.','Run it straight down the inside leg to the stated endpoint and record which endpoint was used.'],tool:'soft_tape',assistance:'assisted',posture:'Stand straight with weight even and legs not bent.',clothing:'Wear close-fitting clothing and no shoes.',preparation:['Sigma records a body inseam; a trouser inseam measured on a garment is a different fact.'],errors:['Starting below the crotch, bending the knee, or silently substituting a garment seam.'],anchor:'Body > Lower limbs',view:'front'},
 'measurement.outseam':{location:'From the anatomical waist level down the outside leg to the floor or stated ankle endpoint.',method:['Locate the Sigma anatomical waist at the side.','Run the tape down the outside of the straight leg.','Record at the chosen endpoint and note it consistently.'],tool:'soft_tape',assistance:'assisted',posture:'Stand upright with feet together and no shoes.',errors:['Starting at a trouser waistband without noting it, following a garment seam, or bending sideways.'],anchor:'Body > Lower limbs',view:'side'},
 'measurement.rise':{location:'Through the crotch from the anatomical waist at the centre front to the anatomical waist at the centre back.',method:['Identify matching anatomical waist points at centre front and centre back.','Pass the tape from front waist through the crotch to back waist.','Keep it comfortably against the body and record the full distance.'],tool:'soft_tape',assistance:'either',posture:'Stand naturally with feet slightly apart.',errors:['Using different front and back waist levels, pulling tight, or substituting a trouser rise.'],anchor:'Body > Lower limbs',view:'side'},
 'measurement.front-rise':{location:'From the anatomical waist at centre front to the crotch junction.',method:['Locate the centre-front anatomical waist.','Run the tape down the torso to the crotch junction.','Record without adding garment ease.'],tool:'soft_tape',assistance:'either',posture:'Stand upright and relaxed.',errors:['Starting at a clothing waistband, stopping short of the crotch junction, or pulling in the abdomen.'],anchor:'Body > Lower limbs',view:'front'},
 'measurement.back-rise':{location:'From the crotch junction to the anatomical waist at centre back.',method:['Locate the crotch junction and centre-back anatomical waist.','Run the tape along the body between those points.','Record while standing naturally.'],tool:'soft_tape',assistance:'assisted',posture:'Stand upright without arching the back.',errors:['Using a trouser waistband, measuring to the hip line, or changing posture.'],anchor:'Body > Lower limbs',view:'back'},
 'measurement.thigh-circumference':tape('Around the fullest part of the upper thigh, below the gluteal fold.',['Stand with weight even.','Wrap the tape around the fullest thigh level.','Keep it horizontal and record without compression.'],'Body > Lower limbs',{errors:['Measuring at the hip crease, shifting weight to one leg, or angling the tape.'],view:'detail'}),
 'measurement.knee-circumference':tape('Around the centre of the knee at kneecap level.',['Stand with the knee straight but not locked.','Wrap the tape around the kneecap and back of the knee at the same level.','Record without compressing.'],'Body > Lower limbs',{errors:['Bending the knee, measuring above or below the kneecap, or pulling tight.'],view:'detail'}),
 'measurement.calf-circumference':tape('Around the fullest part of the calf.',['Stand with weight evenly distributed.','Move the tape to find the maximum calf circumference.','Keep it perpendicular to the leg and record.'],'Body > Lower limbs',{errors:['Measuring only at a fixed height without finding the fullest point or rising onto the toes.'],view:'detail'}),
 'measurement.ankle-circumference':tape('Around the narrowest part of the ankle just above the ankle bones.',['Stand or sit with the foot relaxed.','Wrap the tape around the narrow point above the ankle bones.','Record without including footwear or compressing.'],'Body > Lower limbs',{errors:['Measuring over the ankle bones, socks or footwear, or angling the tape.'],view:'detail'}),
 'measurement.foot-length':{location:'From the back of the heel to the tip of the longest toe while weight-bearing.',method:['Place bare feet on paper or a foot-measuring device with the heel settled.','Stand with weight evenly distributed.','Measure parallel to the foot axis from heel to the longest toe, which may not be the big toe.'],tool:'foot_measuring_device',assistance:'either',posture:'Stand upright with weight on both feet.',clothing:'Bare feet or the consistent thin sock condition noted with the record.',errors:['Measuring without weight-bearing, assuming the big toe is longest, or measuring diagonally.'],anchor:'Body > Lower limbs > Foot',view:'top'},
 'measurement.foot-width':{location:'Across the widest weight-bearing part of the forefoot at the ball joints.',method:['Stand with weight evenly distributed.','Locate the widest points at the ball of the foot.','Measure straight across between them.'],tool:'foot_measuring_device',assistance:'either',posture:'Stand naturally with the foot flat.',errors:['Measuring a lifted foot, including bunion padding inconsistently, or measuring diagonally.'],anchor:'Body > Lower limbs > Foot',view:'top'},
 'measurement.foot-circumference':tape('Around the ball of the foot at the widest forefoot joints while weight-bearing.',['Stand with the foot flat.','Wrap the tape around the widest ball joints.','Keep it snug without compressing and record.'],'Body > Lower limbs > Foot',{posture:'Stand with weight evenly distributed.',errors:['Measuring without weight-bearing, placing the tape at the arch, or overtightening.'],view:'detail'}),
 'measurement.arch-length':{location:'From the back of the heel to the centre of the first metatarsal head (ball joint).',method:['Stand with the heel settled and foot weight-bearing.','Locate the ball joint behind the big toe.','Measure along the foot axis from the heel to that joint.'],tool:'foot_measuring_device',assistance:'either',posture:'Stand with the foot flat and weight even.',errors:['Measuring to the toe tip, using a non-weight-bearing foot, or locating the joint inconsistently.'],anchor:'Body > Lower limbs > Foot',view:'side'},
 'measurement.instep-circumference':tape('Around the highest part of the instep and under the foot at the corresponding point.',['Stand with the foot flat.','Pass the tape over the highest instep point and beneath the foot.','Keep the loop upright and record without compression.'],'Body > Lower limbs > Foot',{posture:'Stand with weight evenly distributed.',errors:['Measuring at the ball of the foot, tilting the loop, or lifting the foot.'],view:'detail'}),
};
export const priorityGuidanceIds=Object.freeze(Object.keys(seeds));
export const measurementGuidanceRegistry:Readonly<Record<string,MeasurementGuidance>>=Object.freeze(Object.fromEntries(Object.entries(seeds).map(([id,seed])=>[id,{
 summary:seed.summary??`How to take a consistent ${id.slice(12).replaceAll('-',' ')} measurement.`,location:seed.location,method:seed.method,tool:seed.tool??'soft_tape',assistance:seed.assistance??'either',posture:seed.posture,clothing:seed.clothing,preparation:seed.preparation,commonErrors:seed.errors,
 illustration:{anatomyAnchor:seed.anchor,view:seed.view??'not_defined',status:'approved' as const,assetId:`illustration.${id.slice(12)}`},futureTutorialKey:`guidance.${id.slice(12)}`,
}])));
export const measurementGuidanceFor=(canonicalFactId:string|undefined):MeasurementGuidance|undefined=>canonicalFactId?measurementGuidanceRegistry[canonicalFactId]:undefined;
