import { readThemePreference, resolveTheme, type ThemePreference, writeThemePreference } from '../lib/preferences.js';

type RouteId = 'profiles' | 'measurements' | 'family' | 'privacy' | 'settings';
const nav = [{id:'profiles',label:'Profiles',short:'Profiles'},{id:'measurements',label:'Measurements & Sizes',short:'Sizes'},{id:'family',label:'Family',short:'Family'},{id:'privacy',label:'Privacy',short:'Privacy'},{id:'settings',label:'Settings',short:'Settings'}] as const;
const pages: Record<Exclude<RouteId,'settings'>, {kicker:string;title:string;description:string;eyebrow:string;emptyTitle:string;body:string;bullets:string[]}> = {
 profiles:{kicker:'Person first',title:'Profiles',description:'A future home for your own record, managed dependant records and connected independent adults.',eyebrow:'Profiles',emptyTitle:'Start with people, not accounts.',body:'Sigma will treat individual, managed and connected profiles as first-class concepts. Ticket 1 does not create stored profiles yet, so there is no fake account setup or cloud sign-in.',bullets:[]},
 measurements:{kicker:'Record keeping',title:'Measurements & Sizes',description:'The future catalogue for physical measurements, standard sizes, brand fit facts and history.',eyebrow:'Measurements',emptyTitle:'Keep the sizes you rarely need but never want to forget.',body:'This shell deliberately stops before the measurement engine. It establishes the destination without pretending records already exist.',bullets:['Physical measurements and standard sizes will arrive in Ticket 2.','Recorded facts will remain distinct from converted display values.','No recommendation logic is implemented or implied.']},
 family:{kicker:'Explicit consent',title:'Family',description:'A future space for trusted groups, managed children and connected adults.',eyebrow:'Family',emptyTitle:'Connection will never mean automatic access.',body:'Sigma is designed for personal and family use equally, but Ticket 1 does not simulate sharing or blanket visibility.',bullets:['Future adult connections require mutual consent.','Family membership must not reveal measurements by default.','Managed child policy remains deliberately unresolved until later product work.']},
 privacy:{kicker:'Ownership',title:'Privacy',description:'The future control room for visibility, consent, export, deletion and permission status.',eyebrow:'Privacy',emptyTitle:'Private by foundation, not by theatre.',body:'This screen communicates the privacy model without claiming production security features that do not yet exist.',bullets:['No telemetry, analytics or advertising trackers are present.','No runtime permissions are requested by this shell.','Export and deletion are product requirements for later data tickets.']}
};
function prefersDark(){return globalThis.matchMedia?.('(prefers-color-scheme: dark)').matches ?? false;}
export function mountApp(root: HTMLElement){let route:RouteId='profiles';let themePreference=readThemePreference();const render=()=>{const resolved=resolveTheme(themePreference,prefersDark());document.documentElement.dataset.theme=resolved;document.documentElement.dataset.themePreference=themePreference;writeThemePreference(themePreference);root.innerHTML=`<div class="app-shell"><aside class="sidebar" aria-label="Primary"><div class="brand"><div class="brand-mark" aria-hidden="true">Σ</div><div><p>Sigma</p><span>Private measurement vault</span></div></div><nav><ul>${nav.map(n=>`<li><button data-route="${n.id}" class="${route===n.id?'active':''}" ${route===n.id?'aria-current="page"':''}><span aria-hidden="true">${icon(n.id)}</span><span class="nav-label">${n.label}</span><span class="nav-short">${n.short}</span></button></li>`).join('')}</ul></nav><div class="sidebar-note"><strong>Local-first shell</strong><span>No account, cloud, analytics, telemetry or runtime permissions.</span></div></aside><main class="content" tabindex="-1">${route==='settings'?settings(themePreference,resolved):page(pages[route])}</main></div>`;root.querySelectorAll<HTMLButtonElement>('[data-route]').forEach(b=>b.addEventListener('click',()=>{route=b.dataset.route as RouteId;render()}));root.querySelectorAll<HTMLInputElement>('input[name="theme"]').forEach(i=>i.addEventListener('change',()=>{themePreference=i.value as ThemePreference;render()}));};render();}
function icon(id:RouteId){return {profiles:'◌',measurements:'⌁',family:'⌂',privacy:'◇',settings:'⚙'}[id];}
function page(p:{kicker:string;title:string;description:string;eyebrow:string;emptyTitle:string;body:string;bullets:string[]}){return `<header class="page-header"><p class="kicker">${p.kicker}</p><h1>${p.title}</h1><p>${p.description}</p></header><section class="empty-state" aria-labelledby="${p.eyebrow}-title"><p class="eyebrow">${p.eyebrow}</p><h2 id="${p.eyebrow}-title">${p.emptyTitle}</h2><div class="empty-copy"><p>${p.body}</p></div>${p.bullets.length?`<ul>${p.bullets.map(b=>`<li>${b}</li>`).join('')}</ul>`:''}</section>`}
function settings(pref:ThemePreference,resolved:'light'|'dark'){return `<header class="page-header"><p class="kicker">Local preferences</p><h1>Settings</h1><p>Shell-level preferences stored locally on this device, without an account or cloud service.</p></header><section class="settings-card" aria-labelledby="theme-heading"><div><p class="eyebrow">Appearance</p><h2 id="theme-heading">Theme preference</h2><p>Choose light, dark or system. The preference is saved locally in this browser for the demo shell.</p></div><fieldset class="theme-options"><legend class="sr-only">Theme preference</legend>${(['system','light','dark'] as ThemePreference[]).map(o=>`<label><input type="radio" name="theme" value="${o}" ${pref===o?'checked':''}/><span>${o[0].toUpperCase()+o.slice(1)}</span></label>`).join('')}</fieldset><p class="metadata">Resolved theme: ${resolved}. Build: Ticket 1 shell.</p></section>`}
