import type { SigmaService } from '../../domain/service.js';
import type { SharingScope } from '../../domain/model.js';
import type { DemoEntitlement } from '../../lib/entitlement.js';
import { categoryOptions, escapeHtml as e, formatDate, header } from './html.js';

export type GrantScopeChoice = 'profile'|'category'|'standard_size'|'brand_fit'|'record:measurement'|'record:standard_size'|'record:brand_fit';
export interface GrantComposerState { ownerId:string; recipientId:string; scope:GrantScopeChoice; category:string; recordId:string }
export const emptyGrantComposerState=():GrantComposerState=>({ownerId:'',recipientId:'',scope:'profile',category:'Footwear',recordId:''});

const name=(data:ReturnType<SigmaService['snapshot']>,id:string)=>e(data.profiles.find((profile)=>profile.id===id)?.displayName??'Unknown');
const possessive=(value:string)=>value.endsWith('s')?`${value}’`:`${value}’s`;

export function renderFamily(service:SigmaService,entitlement:DemoEntitlement,state:GrantComposerState=emptyGrantComposerState()):string {
  const data=service.snapshot(),actor=service.activeActor(),adults=data.profiles.filter((profile)=>profile.profileType==='independent'),unlocked=entitlement!=='free';
  const actorPanel=`<section class="settings-card"><p class="eyebrow">Local demo identity</p><h2>${actor?`Acting as ${e(actor.displayName)}`:'No acting adult selected'}</h2><p>This switch simulates separate adults on one device. It is not authentication or remote consent.</p><label>Switch simulated adult<select id="actor-select">${adults.map((profile)=>`<option value="${profile.id}"${profile.id===actor?.id?' selected':''}>${e(profile.displayName)}</option>`).join('')}</select></label></section>`;
  if(!unlocked)return header('Explicit consent','Family','Connection is not access. Family membership is not blanket sharing.')+actorPanel+`<section class="settings-card"><p class="eyebrow">Demo entitlement · Free</p><h2>Family workflows are locked</h2><p>Personal profiles and existing records remain available. Use the Settings demo control to simulate the Full unlock.</p><button data-route="settings">Open Settings</button></section>`;

  const incoming=data.adultConnections.filter((connection)=>connection.status==='pending'&&connection.recipientProfileId===actor?.id);
  const outgoing=data.adultConnections.filter((connection)=>connection.status==='pending'&&connection.initiatorProfileId===actor?.id);
  const active=data.adultConnections.filter((connection)=>connection.status==='active'&&[connection.initiatorProfileId,connection.recipientProfileId].includes(actor?.id??''));
  const grantViews=service.authorisedGrantHistory();
  const grants=grantViews.map(({grant,canRevoke})=>`<article class="record-card"><h3>${name(data,grant.ownerProfileId)} → ${name(data,grant.recipientProfileId)}</h3><p>${e(scopeLabel(grant.scope))} · <strong>${grant.status==='active'?'Active':'Revoked'}</strong></p><p class="metadata">Granted by ${name(data,grant.grantedByProfileId)} · ${formatDate(grant.grantedAt)}${grant.revokedAt?` · revoked ${formatDate(grant.revokedAt)}`:''}</p>${canRevoke?`<button data-revoke-grant="${grant.id}">Revoke access</button>`:''}</article>`).join('')||'<p>No sharing grants involving this acting adult.</p>';
  const families=data.families.map((family)=>`<article class="record-card"><h3>${e(family.name)}</h3><p>${data.familyMemberships.filter((membership)=>membership.familyId===family.id).map((membership)=>name(data,membership.profileId)).join(', ')}</p><p class="metadata">Membership grants zero record access.</p></article>`).join('')||'<p>No Families yet.</p>';
  const familyOptions=data.families.filter((family)=>data.familyMemberships.some((membership)=>membership.familyId===family.id&&membership.profileId===actor?.id)).map((family)=>`<option value="${family.id}">${e(family.name)}</option>`).join('');
  const availableConnectionTargets=adults.filter((profile)=>profile.id!==actor?.id&&!data.adultConnections.some((connection)=>['pending','active'].includes(connection.status)&&[connection.initiatorProfileId,connection.recipientProfileId].includes(profile.id)&&[connection.initiatorProfileId,connection.recipientProfileId].includes(actor?.id??'')));
  const legacy=data.profiles.filter((profile)=>profile.profileType==='managed'&&!profile.managedByProfileIds?.length).map((profile)=>{const eligible=actor&&data.familyMemberships.some((membership)=>membership.profileId===profile.id&&data.familyMemberships.some((candidate)=>candidate.familyId===membership.familyId&&candidate.profileId===actor.id));return `<p>${e(profile.displayName)} requires explicit management assignment. ${eligible?`<button data-assign-manager="${profile.id}">Assign acting adult</button>`:'Join the same existing Family before assignment.'}</p>`;}).join('');
  const summary=`<section class="family-overview"><p class="eyebrow">1 · Overview</p><h2>A trusted grouping with separate consent boundaries</h2><p>Family membership grants no measurement access. Adult connection requires acceptance and still shares nothing. Records require a separate explicit read-only grant.</p><div class="summary-row"><span><strong>${data.families.length}</strong> Families</span><span><strong>${data.profiles.filter((profile)=>profile.profileType==='managed').length}</strong> managed people</span><span><strong>${incoming.length+outgoing.length}</strong> pending requests</span><span><strong>${active.length}</strong> active connections</span><span><strong>${grantViews.filter(({grant})=>grant.status==='active').length}</strong> relevant active grants</span></div></section>`;

  return header('Explicit consent','Family','A guided same-device demonstration of management, connection and sharing.')+summary+actorPanel+
    `<section class="settings-card"><p class="eyebrow">2 · Families and members</p><h2>Trusted groupings</h2>${families}<form id="family-form" class="inline-form"><label>Family name<input name="name" required></label><button>Create Family</button></form>${familyOptions?`<form id="member-form" class="inline-form"><label>Family<select name="familyId">${familyOptions}</select></label><label>Person<select name="profileId">${data.profiles.map((profile)=>`<option value="${profile.id}">${e(profile.displayName)} · ${profile.profileType==='independent'?'independent adult':'managed person'}</option>`).join('')}</select></label><button>Add member</button></form>`:'<p>Create a Family before adding members.</p>'}</section>`+
    `<section class="settings-card"><p class="eyebrow">3 · Managed children and dependants</p><h2>Management is not sharing</h2><p>The acting adult becomes an authorised manager. Child/dependant is a local management classification, not an account, and other members receive no access.</p>${legacy}${familyOptions?`<form id="managed-form" class="inline-form"><label>Name<input name="displayName" required></label><label>Classification<select name="managedKind"><option value="child">Child</option><option value="dependant">Dependant</option></select></label><label>Eligible Family<select name="familyId">${familyOptions}</select></label><button>Create managed person</button></form>`:'<p>Create or join a Family first.</p>'}</section>`+
    `<section class="settings-card"><p class="eyebrow">4 · Adult connections</p><h2>Mutual acceptance · zero automatic access</h2>${availableConnectionTargets.length?`<form id="connection-form" class="inline-form"><label>Invite another local adult<select name="recipientId">${availableConnectionTargets.map((profile)=>`<option value="${profile.id}">${e(profile.displayName)}</option>`).join('')}</select></label><button>Send request</button></form>`:'<p>No independent adult is currently available for a new request.</p>'}<h3>Incoming request for ${actor?e(actor.displayName):'the acting adult'}</h3>${incoming.map((connection)=>`<p>${name(data,connection.initiatorProfileId)} <button data-respond="${connection.id}" data-accept="true">Accept</button> <button data-respond="${connection.id}" data-accept="false">Decline</button></p>`).join('')||'<p>None.</p>'}<h3>Requests sent</h3>${outgoing.map((connection)=>`<p>Request sent to ${name(data,connection.recipientProfileId)}</p>`).join('')||'<p>None.</p>'}<h3>Accepted</h3>${active.map((connection)=>`<p><strong>${name(data,connection.initiatorProfileId===actor?.id?connection.recipientProfileId:connection.initiatorProfileId)}</strong> · Connected · no records shared <button data-disconnect="${connection.id}">Disconnect</button></p>`).join('')||'<p>None.</p>'}</section>`+
    `<section class="settings-card"><p class="eyebrow">5 · Sharing access</p><h2>Compose an explicit read-only grant</h2>${grants}${renderComposer(service,state)}</section>`;
}

function renderComposer(service:SigmaService,state:GrantComposerState):string {
  const owners=service.grantableOwners();
  if(!owners.length)return '<p>No profile is available for the acting adult to share.</p>';
  const owner=owners.find((profile)=>profile.id===state.ownerId)??owners[0];
  const recipients=service.eligibleGrantRecipients(owner.id);
  if(!recipients.length)return `<p>No eligible recipient is available for ${e(owner.displayName)}. Independent owners require an active adult connection; managed owners follow the existing Family eligibility rule.</p>`;
  const recipient=recipients.find((profile)=>profile.id===state.recipientId)??recipients[0];
  const records=service.grantableRecords(owner.id);
  const recordKind=state.scope.startsWith('record:')?state.scope.slice(7) as 'measurement'|'standard_size'|'brand_fit':undefined;
  const eligibleRecords=recordKind==='measurement'?records.measurements:recordKind==='standard_size'?records.standardSizes:recordKind==='brand_fit'?records.brandFits:[];
  const selectedRecord=eligibleRecords.find((record)=>record.id===state.recordId)??eligibleRecords[0];
  const supplementary=state.scope==='category'?`<label>4. Category<select name="category" id="grant-category">${categoryOptions(state.category)}</select></label>`:recordKind?(eligibleRecords.length?`<label>4. Specific recorded fact<select name="recordId" id="grant-record">${eligibleRecords.map((record)=>`<option value="${record.id}"${record.id===selectedRecord?.id?' selected':''}>${e('label'in record?record.label:record.productName?`${record.brand} · ${record.productName}`:record.brand)}</option>`).join('')}</select></label>`:`<p class="notice">${e(owner.displayName)} has no ${recordKindLabel(recordKind)} available for a specific-record grant.</p>`):'';
  const complete=!recordKind||!!selectedRecord;
  const preview=grantPreview(owner.displayName,recipient.displayName,state.scope,state.category,selectedRecord&&('label'in selectedRecord?selectedRecord.label:selectedRecord.productName?`${selectedRecord.brand} · ${selectedRecord.productName}`:selectedRecord.brand));
  return `<form id="grant-form" class="stacked-form"><label>1. Whose records?<select name="ownerId" id="grant-owner">${owners.map((profile)=>`<option value="${profile.id}"${profile.id===owner.id?' selected':''}>${e(profile.displayName)}</option>`).join('')}</select></label><label>2. Who receives access?<select name="recipientId" id="grant-recipient">${recipients.map((profile)=>`<option value="${profile.id}"${profile.id===recipient.id?' selected':''}>${e(profile.displayName)}</option>`).join('')}</select></label><label>3. What scope?<select name="scopeType" id="grant-scope"><option value="profile"${state.scope==='profile'?' selected':''}>Whole profile</option><option value="category"${state.scope==='category'?' selected':''}>One category</option><option value="standard_size"${state.scope==='standard_size'?' selected':''}>All standard sizes</option><option value="brand_fit"${state.scope==='brand_fit'?' selected':''}>All brand/product fit facts</option><option value="record:measurement"${state.scope==='record:measurement'?' selected':''}>One physical measurement</option><option value="record:standard_size"${state.scope==='record:standard_size'?' selected':''}>One standard size</option><option value="record:brand_fit"${state.scope==='record:brand_fit'?' selected':''}>One brand/product fact</option></select></label>${supplementary}<div class="grant-preview" role="status"><strong>Confirmation</strong><p>${preview.map(e).join('</p><p>')}</p></div><button${complete?'':' disabled'}>Create explicit grant</button></form>`;
}

function grantPreview(owner:string,recipient:string,scope:GrantScopeChoice,category:string,recordLabel?:string):string[]{
  const owned=possessive(owner);
  if(scope==='profile')return [`Share ${owned} entire profile with ${recipient}.`,`${recipient} will receive read-only access to all current recorded facts for ${owner}.`];
  if(scope==='category')return [`Share ${owned} ${category} category with ${recipient}.`,`${recipient} will receive read-only access only to ${owned} recorded facts in ${category}.`];
  if(scope==='standard_size')return [`Share ${owned} standard sizes with ${recipient}.`,'Physical measurements and brand/product facts will remain unshared.'];
  if(scope==='brand_fit')return [`Share ${owned} brand/product facts with ${recipient}.`,'Physical measurements and standard sizes will remain unshared.'];
  return [`Share ${owned} “${recordLabel??'selected record'}” record with ${recipient}.`,'No other records will be included.'];
}
const recordKindLabel=(kind:'measurement'|'standard_size'|'brand_fit')=>kind==='measurement'?'physical measurements':kind==='standard_size'?'standard sizes':'brand/product facts';
export const scopeLabel=(scope:SharingScope)=>scope.type==='profile'?'Entire profile':scope.type==='category'?`Category: ${scope.category}`:scope.type==='record_kind'?`All ${scope.recordKind.replace('_',' ')} records`:`Specific ${scope.recordKind.replace('_',' ')} record`;
