import type { SigmaService } from '../../domain/service.js';
import type { DemoEntitlement } from '../../lib/entitlement.js';
import { escapeHtml as e, header } from './html.js';
const name=(data:ReturnType<SigmaService['snapshot']>,id:string)=>e(data.profiles.find(p=>p.id===id)?.displayName??'Unknown');
export function renderFamily(service:SigmaService, entitlement:DemoEntitlement):string {
 const d=service.snapshot(), actor=service.activeActor(), adults=d.profiles.filter(p=>p.profileType==='independent'), unlocked=entitlement!=='free';
 const actorPanel=`<section class="settings-card"><p class="eyebrow">Local demo identity</p><h2>${actor?`Acting as ${e(actor.displayName)}`:'No acting adult selected'}</h2><p>This switch simulates separate adults on one device. It is not authentication or remote consent.</p><label>Switch simulated adult<select id="actor-select">${adults.map(p=>`<option value="${p.id}"${p.id===actor?.id?' selected':''}>${e(p.displayName)}</option>`).join('')}</select></label></section>`;
 if(!unlocked) return header('Explicit consent','Family','Connection is not access. Family membership is not blanket sharing.')+actorPanel+`<section class="settings-card"><p class="eyebrow">Demo entitlement · Free</p><h2>Family workflows are locked</h2><p>Personal profiles and existing records remain available. Use the Settings demo control to simulate the Full unlock.</p></section>`;
 const incoming=d.adultConnections.filter(c=>c.status==='pending'&&c.recipientProfileId===actor?.id), outgoing=d.adultConnections.filter(c=>c.status==='pending'&&c.initiatorProfileId===actor?.id), active=d.adultConnections.filter(c=>c.status==='active'&&[c.initiatorProfileId,c.recipientProfileId].includes(actor?.id??''));
 const families=d.families.map(f=>`<article class="record-card"><h3>${e(f.name)}</h3><p>${d.familyMemberships.filter(m=>m.familyId===f.id).map(m=>name(d,m.profileId)).join(', ')}</p><p class="metadata">Membership grants zero record access.</p></article>`).join('')||'<p>No Families yet.</p>';
 const grants=d.sharingGrants.map(g=>`<article class="record-card"><h3>${name(d,g.ownerProfileId)} → ${name(d,g.recipientProfileId)}</h3><p>${e(scopeLabel(g.scope))} · ${g.status}</p><p class="metadata">Granted by ${name(d,g.grantedByProfileId)} on ${e(g.grantedAt)}</p>${g.status==='active'&&g.grantedByProfileId===actor?.id?`<button data-revoke-grant="${g.id}">Revoke access</button>`:''}</article>`).join('')||'<p>No sharing grants. Connections and membership expose nothing by themselves.</p>';
 const familyOptions=d.families.filter(f=>d.familyMemberships.some(m=>m.familyId===f.id&&m.profileId===actor?.id)).map(f=>`<option value="${f.id}">${e(f.name)}</option>`).join('');
 const ownerOptions=d.profiles.filter(p=>p.id===actor?.id||(p.profileType==='managed'&&p.managedByProfileIds?.includes(actor?.id??''))).map(p=>`<option value="${p.id}">${e(p.displayName)}</option>`).join('');
 const recipientOptions=adults.filter(p=>p.id!==actor?.id).map(p=>`<option value="${p.id}">${e(p.displayName)}</option>`).join('');
 const legacy=d.profiles.filter(p=>p.profileType==='managed'&&!(p.managedByProfileIds?.length)).map(p=>`<p>${e(p.displayName)} requires explicit management assignment. <button data-assign-manager="${p.id}">Assign acting adult</button></p>`).join('');
 return header('Explicit consent','Family','Connection is not access. No data is shared by default.')+actorPanel+`<div class="page-grid"><section class="settings-card"><h2>Families</h2>${families}<form id="family-form" class="inline-form"><label>Name<input name="name" required></label><button>Create Family</button></form><form id="member-form" class="inline-form"><select name="familyId">${familyOptions}</select><select name="profileId">${d.profiles.map(p=>`<option value="${p.id}">${e(p.displayName)}</option>`).join('')}</select><button>Add member</button></form></section><section class="settings-card"><h2>Adult connections</h2><form id="connection-form" class="inline-form"><select name="recipientId">${recipientOptions}</select><button>Send request</button></form><h3>Incoming pending</h3>${incoming.map(c=>`<p>${name(d,c.initiatorProfileId)} <button data-respond="${c.id}" data-accept="true">Accept</button> <button data-respond="${c.id}" data-accept="false">Decline</button></p>`).join('')||'<p>None.</p>'}<h3>Outgoing pending</h3>${outgoing.map(c=>`<p>Waiting for ${name(d,c.recipientProfileId)}</p>`).join('')||'<p>None.</p>'}<h3>Active connections</h3>${active.map(c=>`<p>${name(d,c.initiatorProfileId===actor?.id?c.recipientProfileId:c.initiatorProfileId)} · zero automatic access <button data-disconnect="${c.id}">Disconnect</button></p>`).join('')||'<p>None.</p>'}</section></div><section class="settings-card"><h2>Managed children & dependants</h2>${legacy}<form id="managed-form" class="inline-form"><input name="displayName" required placeholder="Name"><select name="managedKind"><option value="child">Child</option><option value="dependant">Dependant</option></select><select name="familyId">${familyOptions}</select><button>Create with acting adult as manager</button></form></section><section class="settings-card"><h2>Granular sharing & audit history</h2>${grants}<form id="grant-form" class="inline-form"><label>Owner<select name="ownerId">${ownerOptions}</select></label><label>Recipient<select name="recipientId">${recipientOptions}</select></label><label>Scope<select name="scopeType"><option value="profile">Entire profile</option><option value="category">Measurement category</option><option value="standard_size">All standard sizes</option><option value="brand_fit">All brand/product fit</option></select></label><input name="category" placeholder="Category when selected"><button>Create explicit grant</button></form></section>`;
}
export const scopeLabel=(s:ReturnType<SigmaService['snapshot']>['sharingGrants'][number]['scope'])=>s.type==='profile'?'Entire profile':s.type==='category'?`Category: ${s.category}`:s.type==='record_kind'?`All ${s.recordKind.replace('_',' ')} records`:`Specific ${s.recordKind.replace('_',' ')} record`;
