import type { SigmaService } from '../../domain/service.js';
import { escapeHtml as e, header } from './html.js';

export function renderProfiles(service:SigmaService,editingId='',formOpen=false):string {
  const data=service.snapshot(),visible=service.visibleProfiles(),requested=data.profiles.find((profile)=>profile.id===editingId),editing=visible.find((profile)=>profile.id===editingId),unsafe=['corrupt','unsupported_version'].includes(service.storageStatus().status);
  const cards=visible.map((profile)=>{const records=service.authorisedRecords(profile.id),access=service.profileAccess(profile.id),total=records.measurements.length+records.standardSizes.length+records.brandFits.length;return `<article class="profile-row ${profile.id===data.activeProfileId?'selected':''}"><div><h2>${e(profile.displayName)}</h2><p>${e(profile.relationshipLabel||(profile.profileType==='managed'?`Managed ${profile.managedKind??'dependant'}`:'Personal profile'))} · ${access==='editable'?'Editable':'Shared read-only'}</p><small>${total} record${total===1?'':'s'}</small></div><div class="button-row"><button class="secondary" data-select-profile="${profile.id}">View records</button>${access==='editable'?`<button class="quiet" data-edit-profile="${profile.id}">Edit</button>`:''}${profile.profileType==='managed'?'<button class="quiet" data-family-view="people">Family</button>':''}</div></article>`;}).join('');
  const canEdit=!requested||!!editing&&service.canManageProfile(editing.id);
  const form=formOpen||editing?`<section class="form-card form-panel" id="profile-form-panel" tabindex="-1"><h2>${editing?`Edit ${e(editing.displayName)}`:'Add profile'}</h2>${canEdit?`${editing?'<p class="metadata">Profile type cannot be changed here.</p>':''}<form id="profile-form" class="stacked-form"><label>Display name<input name="displayName" required value="${e(editing?.displayName)}"></label>${editing?'':'<input type="hidden" name="profileType" value="independent">'}<label>Relationship label <span>optional</span><input name="relationshipLabel" value="${e(editing?.relationshipLabel)}"></label><label>Date of birth <span>optional</span><input type="date" name="dateOfBirth" value="${e(editing?.dateOfBirth)}"></label><label>Notes <span>optional</span><textarea name="notes">${e(editing?.notes)}</textarea></label><div class="button-row"><button type="submit" class="primary">${editing?'Save':'Create profile'}</button><button type="button" class="quiet" id="cancel-profile-form">Cancel</button></div></form>${editing?`<button type="button" class="danger" data-delete-profile="${editing.id}">Delete profile</button>`:''}`:'<p>You cannot edit this profile.</p>'}</section>`:'';
  if(!data.profiles.length&&!unsafe)return header('Profiles','People','Choose a person, then retrieve their recorded facts.')+`<section class="first-use"><img class="anatomy-mark" src="/body-outline.svg" alt="" aria-hidden="true"><div><h2>Keep useful measurements and sizes on this device.</h2><p>No accounts exist on this device yet. Create the first one; Family is optional.</p>${formOpen?form:'<button class="primary" id="open-profile-form">Create my profile</button>'}</div></section>`;
  return header('Profiles','People','Choose a person or add another personal profile.')+`<div class="profiles-toolbar"><div><strong>People</strong><span>${visible.length} available</span></div>${!formOpen&&!editing?'<button class="primary" id="open-profile-form">Add profile</button>':''}</div>${cards||'<div class="empty-inline"><p>You do not have access to a profile right now.</p></div>'}${form}`;
}
