import type { SigmaService } from '../../domain/service.js';
import { escapeHtml as e, header } from './html.js';
export function renderProfiles(service: SigmaService, editingId: string): string {
  const data = service.snapshot(); const visible=service.visibleProfiles(); const requested=data.profiles.find((profile)=>profile.id===editingId); const editing = visible.find((profile) => profile.id === editingId); const unsafe = ['corrupt', 'unsupported_version'].includes(service.storageStatus().status);
  const cards = visible.map((profile) => { const records=service.authorisedRecords(profile.id); const access=service.profileAccess(profile.id); return `<article class="record-card ${profile.id === data.activeProfileId ? 'selected' : ''}"><div><p class="eyebrow">${profile.profileType === 'independent' ? 'Independent adult' : `Managed ${e(profile.managedKind??'dependant')}`} · ${access==='editable'?'You can manage':'Shared read-only'}</p><h2>${e(profile.displayName)}</h2><p>${e(profile.relationshipLabel || (profile.profileType === 'managed' ? 'Locally managed person' : 'Personal profile'))}</p><p class="metadata">${records.measurements.length} physical · ${records.standardSizes.length} standard size${records.standardSizes.length===1?'':'s'} · ${records.brandFits.length} brand/product fact${records.brandFits.length===1?'':'s'}</p></div><div class="button-row"><button class="secondary" data-select-profile="${profile.id}">View records</button>${access==='editable'?`<button class="quiet" data-edit-profile="${profile.id}">Edit profile details</button>`:''}${profile.profileType==='managed'?'<button class="quiet" data-route="family">Family management</button>':''}</div></article>`; }).join('');
  const canEdit=!requested||!!editing&&service.canManageProfile(editing.id); const form = unsafe ? `<section class="form-card"><p>Creating profiles is disabled until the unreadable stored value is explicitly reset.</p></section>` : `<section class="form-card"><p class="eyebrow">${editing ? 'Edit profile metadata' : 'New independent profile'}</p><h2>${editing ? `Update ${e(editing.displayName)}` : 'Create a local adult identity'}</h2>${canEdit?`<form id="profile-form" class="stacked-form"><label>Display name<input name="displayName" required value="${e(editing?.displayName)}"></label>${editing?'':'<input type="hidden" name="profileType" value="independent">'}<label>Relationship label <span>optional</span><input name="relationshipLabel" value="${e(editing?.relationshipLabel)}"></label><label>Date of birth <span>optional</span><input type="date" name="dateOfBirth" value="${e(editing?.dateOfBirth)}"></label><label>Notes <span>optional</span><textarea name="notes">${e(editing?.notes)}</textarea></label><button type="submit">${editing ? 'Save metadata' : 'Create profile'}</button></form>`:'<p>The acting adult is not authorised to edit this profile.</p>'}<p class="metadata">Profile type cannot be changed through ordinary editing. Managed people are created in Family with explicit authority.</p></section>`;
  const firstUse=!unsafe&&!data.profiles.length?`<section class="first-use"><p class="eyebrow">Private by default</p><h2>Start with a person, not an account.</h2><p>Sigma stores physical measurements and practical sizes locally. No account is required. Start with your independent personal profile; Family features are optional and can be explored later.</p><button data-start-profile> Create my personal profile</button></section>`:'';
  const next=data.profiles.length===1&&!data.measurements.length&&!data.standardSizes.length&&!data.brandFits.length?'<div class="notice"><strong>Profile ready.</strong> Add your first recorded fact when you are ready. <button data-route="measurements">Add first record</button></div>':'';
  return header('Person first', 'Profiles', 'Choose whose facts you want to retrieve. Personal use never requires Family setup.') + firstUse+next+`<div class="page-grid"><section><div class="section-heading"><div><p class="eyebrow">People available to the acting adult</p><h2>${visible.length ? 'Choose a person' : 'No available profiles'}</h2></div></div>${cards || `<div class="empty-inline"><p>${unsafe ? 'Stored data is present but cannot be shown safely.' : 'Create your independent profile to begin.'}</p></div>`}</section>${form}</div>`;
}
