import type { SigmaService } from '../../domain/service.js';
import { currentMeasurementValue, type BrandFit, type MeasurementValue, type PhysicalMeasurement, type Profile, type StandardSize } from '../../domain/model.js';
import { measurementOptions } from '../../domain/taxonomy.js';
import { canonicalFactById, canonicalFactsFor, type CanonicalFactDefinition, type CanonicalRecordKind } from '../../domain/canonical-facts.js';
import { measurementGuidanceFor, type GuidanceAssistance, type GuidanceTool, type MeasurementGuidance } from '../../domain/measurement-guidance.js';
import { formatConvertedValue, measurementDimension, measurementSemantics, unitsForDimension, type ConversionResult, type Dimension } from '../../conversion/registry.js';
import { categoryOptions, disclosure, empty, escapeHtml as e, formatDate, header, sourceLabel, today, unitSpan } from './html.js';
import { renderAnatomyIllustration } from './anatomy-illustration.js';
import { anatomyChildRegions, anatomyFactsAtPath, anatomyPathKey } from '../../domain/anatomy-discovery.js';
import type { AnatomyPath } from '../../domain/canonical-facts.js';
import { renderAnatomyNavigator } from './anatomy-navigator.js';
export type RecordMode = 'measurement' | 'standard_size' | 'brand_fit';
export const modeLabel = (mode: RecordMode) => mode === 'measurement' ? 'Physical measurements' : mode === 'standard_size' ? 'Standard sizes' : 'Brand & product facts';
export function renderRecords(service: SigmaService, mode: RecordMode, search: string, category: string, creationOpen=true): string {
  const profile = service.activeVisibleProfile();
  if (!profile) return header('Record keeping', 'Measurements & Sizes', 'Recorded facts remain separate and local.') + empty('No profile available', 'Create a personal profile, or ask someone to share theirs with you.', 'Hidden profiles and their records stay hidden.');
  const records = service.authorisedRecords(profile.id, search, category); const count = records[mode === 'measurement' ? 'measurements' : mode === 'standard_size' ? 'standardSizes' : 'brandFits'].length; const canEdit=service.canManageProfile(profile.id);
  const filtered=!!(search||category);
  const sharedEmpty=service.profileAccess(profile.id)==='read_only'&&!records.measurements.length&&!records.standardSizes.length&&!records.brandFits.length;
  const emptyVisual=mode==='measurement'&&!filtered&&!sharedEmpty?'<img class="anatomy-empty" src="/body-outline.svg" alt="Abstract body outline">':'';
  return header('Records', 'Measurements & Sizes', `${e(profile.displayName)} · ${canEdit?'Editable':'Shared read-only'}`) + `${canEdit?'':`<p class="notice">Only what has been shared with you is shown here. You cannot edit it.</p>`}<label class="mobile-mode-select">Record type<select id="record-mode-select"><option value="measurement"${mode==='measurement'?' selected':''}>Physical</option><option value="standard_size"${mode==='standard_size'?' selected':''}>Standard sizes</option><option value="brand_fit"${mode==='brand_fit'?' selected':''}>Brand &amp; product facts</option></select></label><div class="record-tabs" role="group" aria-label="Recorded fact type"><button data-record-mode="measurement" class="secondary ${mode === 'measurement' ? 'active' : ''}">Physical</button><button data-record-mode="standard_size" class="secondary ${mode === 'standard_size' ? 'active' : ''}">Standard sizes</button><button data-record-mode="brand_fit" class="secondary ${mode === 'brand_fit' ? 'active' : ''}">Brand &amp; product facts</button></div><div class="toolbar"><label>Search<input id="record-search" value="${e(search)}" autocomplete="off"></label><label>Category<select id="category-filter"><option value="">All categories</option>${categoryOptions(category)}</select></label>${filtered?`<span class="filter-state">${search?`“${e(search)}”`:''}${category?` · ${e(category)}`:''}</span><button class="quiet" id="clear-record-filters">Clear</button>`:''}${canEdit&&!creationOpen?'<button class="primary" id="open-record-form">Add record</button>':''}</div>${creationOpen&&canEdit?renderForm(profile,mode):''}<section><div class="section-heading"><h2>${modeLabel(mode)}</h2><span>${count}</span></div>${count?renderList(mode, records, service):`<div class="empty-inline record-empty">${emptyVisual}<p>${filtered?'No matching records.':sharedEmpty?'This profile is shared with you, but nothing here matches what was shared.':`No ${modeLabel(mode).toLowerCase()} recorded yet.`}</p></div>`}</section>`;
}
function renderList(mode: RecordMode, records: ReturnType<SigmaService['records']>, service: SigmaService): string { const editable=service.activeVisibleProfile()?service.canManageProfile(service.activeVisibleProfile()!.id):false; if (mode === 'measurement') return records.measurements.map((record) => renderMeasurementCompact(record, service,editable)).join('') || none('physical measurements'); if (mode === 'standard_size') return records.standardSizes.map((record) => renderSizeCompact(record, service,editable)).join('') || none('standard sizes'); return records.brandFits.map((record) => renderBrandCompact(record, service,editable)).join('') || none('brand & product facts'); }

function renderMeasurementCompact(record:PhysicalMeasurement,service:SigmaService,editable:boolean):string {
  const current=currentMeasurementValue(record),history=[...record.values].sort((a,b)=>b.measuredAt.localeCompare(a.measuredAt)||b.recordedAt.localeCompare(a.recordedAt)),conversions=service.measurementConversions(record.id),first=conversions[0],sameDate=current&&record.values.filter((value)=>!value.correction&&value.measuredAt===current.measuredAt).length>1;
  const value=current?`${current.originalValue} ${e(current.originalUnit)}`:'No current value';
  const displayValue=current?`${e(String(current.originalValue))}${unitSpan(current.originalUnit)}`:'No current value';
  return `<article class="record-card compact-record" id="record-${record.id}" tabindex="-1"><div class="record-title"><div><h3>${e(record.label)}</h3><p>${e(record.category)} · ${current?`Measured ${formatDate(current.measuredAt)}`:'All entries corrected'}</p></div><strong class="record-value">${displayValue}</strong></div>${first?`<p class="quick-conversion">${formatConversion(first)} <small>${first.exact?'Exact':'Approximate'}</small></p>`:''}<div class="record-actions">${editable?`<details><summary>Update value</summary><form class="inline-form" data-history-form="${record.id}"><label>Value<input name="value" type="number" step="any" required></label><label>Unit${unitControl(measurementDimension(record.measurementType),current?.originalUnit??'cm')}</label><label>Measured on<input name="measuredAt" type="date" required value="${today()}"></label><label>Notes<input name="notes"></label><button class="primary">Add value</button></form></details>`:''}${renderSavedGuidance(record.canonicalFactId)}${renderRecordDetails(conversions,`Calculated from recorded ${value}`,'Display values',current?sourceDetail(current):'No valid current entry.')}<details><summary>History (${history.length})</summary>${sameDate?'<p class="metadata">Entries measured on the same date use the most recently recorded valid entry as current.</p>':''}<ol class="history-list">${history.map((item)=>renderHistoryItem(record.id,item,current,editable,history.length>1)).join('')}</ol></details>${editable?`<details><summary>Edit</summary><form class="inline-form compact-edit" data-edit-measurement-form="${record.id}"><label>Label<input name="label" required value="${e(record.label)}"></label><label>Type<input name="measurementType" required value="${e(record.measurementType)}"></label><label>Category<select name="category">${categoryOptions(record.category)}</select></label><button class="primary">Save</button></form><button type="button" class="danger" data-delete-measurement="${record.id}">Delete record</button></details>`:''}</div></article>`;
}
function renderHistoryItem(recordId:string,item:MeasurementValue,current:MeasurementValue|undefined,editable:boolean,canDelete:boolean):string {
  const status=item.id===current?.id?'Current':item.correction?'Incorrect':'Earlier';
  const deleteButton=editable&&canDelete?`<button type="button" class="quiet" data-delete-value="${recordId}" data-value-id="${item.id}">Delete</button>`:'';
  return `<li class="history-entry ${item.correction?'corrected-entry':''}"><div class="history-entry-main"><strong class="history-value">${e(String(item.originalValue))}${unitSpan(item.originalUnit)}</strong><span class="history-status">${status}</span></div><dl class="history-metadata"><div><dt>Measured</dt><dd>${formatDate(item.measuredAt)}</dd></div><div><dt>Recorded</dt><dd>${formatDate(item.recordedAt)}</dd></div>${item.correction?`<div><dt>Marked incorrect</dt><dd>${formatDate(item.correction.correctedAt)}</dd></div><div><dt>Reason</dt><dd>${e(item.correction.reason||'No reason supplied')}</dd></div>`:''}</dl>${editable&&!item.correction?`<form data-correct-value-form="${recordId}" data-value-id="${item.id}" class="correction-form"><label>Correction reason <span>optional</span><input name="reason"></label><button class="secondary">Mark incorrect</button>${deleteButton}</form>`:deleteButton}</li>`;
}
function canonicalEditFields(record:StandardSize|BrandFit):string {const definition=record.canonicalFactId?canonicalFactById(record.canonicalFactId):undefined,systems=definition?.standardSize?.permittedSystems??definition?.brandProduct?.permittedSystems;if(!definition||!systems)return `<label>Category<select name="category">${categoryOptions(record.category)}</select></label><label>System<input name="sizingSystem" value="${e(record.sizingSystem)}"></label>`;return `<input type="hidden" name="category" value="${e(definition.category)}"><p class="metadata">Canonical category: ${e(definition.category)}</p><label>System<select name="sizingSystem">${systems.map(system=>`<option${system===record.sizingSystem?' selected':''}>${e(system)}</option>`).join('')}</select></label>`;}
function renderSizeCompact(record:StandardSize,service:SigmaService,editable:boolean):string {const conversions=service.standardSizeConversions(record.id),first=conversions[0],canonical=record.canonicalFactId?canonicalFactById(record.canonicalFactId):undefined;return `<article class="record-card compact-record"><div class="record-title"><div><h3>${e(record.label)}</h3><p>${e(record.category)} · Recorded ${formatDate(record.recordedAt)}</p></div><strong class="record-value">${unitSpan(record.sizingSystem)} ${e(record.sizeValue)}</strong></div>${first?`<p class="quick-conversion">${formatConversion(first)} <small>Approximate</small></p>`:''}<div class="record-actions">${renderRecordDetails(conversions,`Derived from recorded ${e(record.sizingSystem)} ${e(record.sizeValue)}`,'Standard equivalents',sourceLabel(record.sourceType,record.sourceName))}${editable?`<details><summary>Edit</summary><form class="inline-form compact-edit" data-edit-size-form="${record.id}">${canonical?`<input type="hidden" name="label" value="${e(canonical.label)}"><p class="metadata">Canonical fact: ${e(canonical.label)}</p>`:`<label>Label<input name="label" value="${e(record.label)}"></label>`}${canonicalEditFields(record)}<label>Size<input name="sizeValue" value="${e(record.sizeValue)}"></label><label>Notes<input name="notes" value="${e(record.notes)}"></label><button class="primary">Save</button></form><button type="button" class="danger" data-delete-size="${record.id}">Delete record</button></details>`:''}</div></article>`;}
function renderBrandCompact(record:BrandFit,service:SigmaService,editable:boolean):string {const conversions=service.brandFitConversions(record.id),first=conversions[0];return `<article class="record-card compact-record"><div class="record-title"><div><h3>${e(record.brand)}${record.productName?` · ${e(record.productName)}`:''}</h3><p>${e(record.category)} · Recorded ${formatDate(record.recordedAt)}</p></div><strong class="record-value">${unitSpan(record.sizingSystem)} ${e(record.sizeValue)}</strong></div>${first?`<p class="quick-conversion">${formatConversion(first)} <small>Approximate · not a fit prediction</small></p>`:''}<div class="record-actions">${renderRecordDetails(conversions,`Derived from recorded standard · not a fit prediction`,'Standard equivalents',sourceLabel(record.sourceType,record.sourceName))}${editable?`<details><summary>Edit</summary><form class="inline-form compact-edit" data-edit-brand-form="${record.id}"><label>Brand<input name="brand" value="${e(record.brand)}"></label><label>Product<input name="productName" value="${e(record.productName)}"></label><label>Line<input name="productLine" value="${e(record.productLine)}"></label>${canonicalEditFields(record)}<label>Size<input name="sizeValue" value="${e(record.sizeValue)}"></label><label>Fit notes<input name="fitNotes" value="${e(record.fitNotes)}"></label><button class="primary">Save</button></form><button type="button" class="danger" data-delete-brand="${record.id}">Delete record</button></details>`:''}</div></article>`;}
function formatConversion(result:ConversionResult):string{return `${typeof result.outputValue==='number'?formatConvertedValue(result.outputValue,result.outputSystem.includes('mm')?'mm':result.outputSystem):e(result.outputValue)} ${e(result.outputSystem)}`;}
function sourceDetail(value:ReturnType<typeof currentMeasurementValue>):string {return value?`${value.derivation?.kind==='derived'?'Derived':'Recorded directly'} · ${sourceLabel(value.sourceType,value.sourceName)}${value.sourceDevice?` · ${e(value.sourceDevice)}`:''}${value.confidence!==undefined?` · ${Math.round(value.confidence*100)}% confidence`:''}`:'';}
function renderRecordDetails(conversions:ConversionResult[],conversionProvenance:string,conversionHeading:string,sourceText:string):string {
  const conversionsHtml=conversions.length?renderConversions(conversions,conversionProvenance,conversionHeading):'';
  return disclosure('Details',`${conversionsHtml}<section class="record-detail-source"><h4>Source</h4><p class="metadata">${sourceText}</p></section>`);
}
function renderMeasurement(record: PhysicalMeasurement, service: SigmaService, editable=true): string { const current = currentMeasurementValue(record)!; const history = [...record.values].sort((a, b) => b.measuredAt.localeCompare(a.measuredAt)||b.recordedAt.localeCompare(a.recordedAt)); const conversions = service.measurementConversions(record.id); const dimension = measurementDimension(record.measurementType); const provenance=(value:typeof current)=>`${value.derivation?.kind==='derived'?'Derived':'Recorded directly'} · ${sourceLabel(value.sourceType,value.sourceName)}${value.sourceItemId?` · source item ${e(value.sourceItemId)}`:''}${value.sourceDevice?` · device ${e(value.sourceDevice)}`:''}${value.confidence!==undefined?` · confidence ${Math.round(value.confidence*100)}%`:''}`; return `<article class="record-card"><div class="record-title"><div><p class="eyebrow">${e(record.category)}</p><h3>${e(record.label)}</h3></div><div><span class="value-label">Current recorded value</span><strong class="record-value">${e(String(current.originalValue))}${unitSpan(current.originalUnit)}</strong></div></div><p class="metadata">Measured ${formatDate(current.measuredAt)} · recorded ${formatDate(current.recordedAt)} · ${provenance(current)}</p>${renderConversions(conversions, `Transient display from recorded ${current.originalValue} ${e(current.originalUnit)}`, 'Converted display values')}${!conversions.length ? unsupported() : ''}<details><summary>History & provenance (${history.length})</summary><ol class="history-list">${history.map((value) => `<li><strong>${e(String(value.originalValue))}${unitSpan(value.originalUnit)}</strong><span>${value.id === current.id ? 'Current recorded value · ' : ''}measured ${formatDate(value.measuredAt)}</span><small>${provenance(value)} · recorded ${formatDate(value.recordedAt)}</small></li>`).join('')}</ol>${editable?`<form class="inline-form" data-history-form="${record.id}"><label>Recorded value<input name="value" type="number" step="any" required></label><label>Unit${unitControl(dimension, current.originalUnit)}</label><label>Measured on<input name="measuredAt" type="date" required value="${today()}"></label><label>Notes<input name="notes"></label><button>Add measurement value</button></form>`:''}</details>${editable?`<details><summary>Edit measurement metadata</summary><form class="inline-form compact-edit" data-edit-measurement-form="${record.id}"><label>Label<input name="label" required value="${e(record.label)}"></label><label>Type<input name="measurementType" required value="${e(record.measurementType)}"></label><label>Category<select name="category">${categoryOptions(record.category)}</select></label><button>Save metadata</button></form></details>`:''}</article>`; }
function renderSize(record: StandardSize, service: SigmaService, editable=true): string { const conversions = service.standardSizeConversions(record.id); const provenance=`${record.derivation?.kind==='derived'?'Derived':'Recorded directly'} · ${sourceLabel(record.sourceType,record.sourceName)}${record.sourceDevice?` · device ${e(record.sourceDevice)}`:''}${record.confidence!==undefined?` · confidence ${record.confidence}`:''}`; return `<article class="record-card"><div class="record-title"><div><p class="eyebrow">${e(record.category)}</p><h3>${e(record.label)}</h3></div><strong class="record-value">${unitSpan(record.sizingSystem)} ${e(record.sizeValue)}</strong></div><p class="metadata">${provenance} · recorded ${formatDate(record.recordedAt)}</p>${renderConversions(conversions, `Converted from recorded ${e(record.sizingSystem)} ${e(record.sizeValue)}`, 'Standard equivalents')}${!conversions.length ? unsupported() : ''}${editable?`<details><summary>Edit recorded size</summary><form class="inline-form compact-edit" data-edit-size-form="${record.id}"><label>Label<input name="label" value="${e(record.label)}"></label><label>Category<select name="category">${categoryOptions(record.category)}</select></label><label>System<input name="sizingSystem" value="${e(record.sizingSystem)}"></label><label>Size<input name="sizeValue" value="${e(record.sizeValue)}"></label><label>Notes<input name="notes" value="${e(record.notes)}"></label><button>Save edit</button></form></details>`:''}</article>`; }
function renderBrand(record: BrandFit, service: SigmaService, editable=true): string { const conversions = service.brandFitConversions(record.id); return `<article class="record-card"><div class="record-title"><div><p class="eyebrow">${e(record.category)}</p><h3>${e(record.brand)}${record.productName ? ` · ${e(record.productName)}` : ''}</h3></div><strong class="record-value">${unitSpan(record.sizingSystem)} ${e(record.sizeValue)}</strong></div><p class="metadata">Recorded fact · ${formatDate(record.recordedAt)} · ${sourceLabel(record.sourceType, record.sourceName)}</p>${renderConversions(conversions, `Derived from recorded ${e(record.sizingSystem)} ${e(record.sizeValue)} · not a prediction of fit for this brand or product`, 'Generic standard equivalents')}${!conversions.length ? unsupported() : ''}${editable?`<details><summary>Edit recorded fact</summary><form class="inline-form compact-edit" data-edit-brand-form="${record.id}"><label>Brand<input name="brand" value="${e(record.brand)}"></label><label>Product<input name="productName" value="${e(record.productName)}"></label><label>Line<input name="productLine" value="${e(record.productLine)}"></label><label>Category<select name="category">${categoryOptions(record.category)}</select></label><label>System<input name="sizingSystem" value="${e(record.sizingSystem)}"></label><label>Size<input name="sizeValue" value="${e(record.sizeValue)}"></label><label>Fit notes<input name="fitNotes" value="${e(record.fitNotes)}"></label><button>Save edit</button></form></details>`:''}</article>`; }
function renderAnatomyDiscovery():string {
  const panels:string[]=[];
  const visit=(path:AnatomyPath):void=>{
    const key=anatomyPathKey(path),children=anatomyChildRegions(path),facts=anatomyFactsAtPath(path),parent=path.length>1?path.slice(0,-1) as unknown as AnatomyPath:undefined;
    const regionLabel=path.length===1?'Body':path.at(-1)!;
    const regions=children.map((child)=>`<button type="button" class="anatomy-region-choice" data-anatomy-path="${e(anatomyPathKey(child))}" aria-label="Browse ${e(child.at(-1)!)}"><span>${e(child.at(-1)!)}</span><span aria-hidden="true">›</span></button>`).join('');
    const measurements=facts.map((fact)=>`<button type="button" class="anatomy-fact-choice" data-anatomy-fact="${fact.id}">${e(fact.label)}<span>${e(fact.category)}</span></button>`).join('');
    panels.push(`<section class="anatomy-discovery-panel" data-anatomy-panel="${e(key)}"${key==='Body'?'':' hidden'} aria-labelledby="anatomy-heading-${panels.length}">${parent?`<button type="button" class="quiet anatomy-back" data-anatomy-path="${e(anatomyPathKey(parent))}" aria-label="Back to ${e(parent.at(-1)!)}">← Back to ${e(parent.at(-1)!)}</button>`:''}<p class="eyebrow">${e(path.join(' · '))}</p><h4 id="anatomy-heading-${panels.length}">${e(regionLabel)}</h4>${facts.length?`<div class="anatomy-fact-list" aria-label="Measurements for ${e(regionLabel)}">${measurements}</div>`:''}${children.length?`<div class="anatomy-region-list" aria-label="Body regions within ${e(regionLabel)}">${regions}</div>`:''}</section>`);
    children.forEach(visit);
  };
  visit(['Body']);
  return `<section id="anatomy-discovery-browser" hidden aria-label="Browse measurements by body region"><div class="anatomy-browser-heading"><div><p class="eyebrow">Find measurement</p><h3>Browse by body</h3></div><button type="button" class="quiet" id="close-anatomy-discovery">Close</button></div><p class="metadata">Pick a body region, then a measurement.</p><div class="anatomy-browser-layout"><div id="anatomy-navigator-stage">${renderAnatomyNavigator()}</div><div class="anatomy-semantic-browser">${panels.join('')}</div></div></section>`;
}
function renderAnatomyToggle():string {
  return `<div class="entry-toggle" role="group" aria-label="Find a measurement"><span class="entry-toggle-current" aria-hidden="true">Search by name</span><button type="button" class="secondary" id="open-anatomy-discovery" aria-expanded="false" aria-controls="anatomy-discovery-browser">Browse by body</button></div>`;
}
function renderForm(profile: Profile, mode: RecordMode): string {
  const kind:CanonicalRecordKind=mode==='brand_fit'?'brand_product_fact':mode;
  const byCategory=new Map<string,CanonicalFactDefinition[]>();
  for(const fact of canonicalFactsFor(kind)){const list=byCategory.get(fact.category)??[];list.push(fact);byCategory.set(fact.category,list);}
  const options=[...byCategory.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([groupCategory,facts])=>`<optgroup label="${e(groupCategory)}">${facts.map((fact)=>`<option value="${fact.id}" data-search="${e([fact.label,fact.category,...fact.aliases,fact.description].filter(Boolean).join(' ').toLowerCase())}" data-choices="${e((fact.measurement?.permittedUnits??fact.standardSize?.permittedSystems??fact.brandProduct?.permittedSystems??[]).join('|'))}" data-default-choice="${e(fact.measurement?.defaultUnit??fact.standardSize?.defaultSystem??fact.brandProduct?.permittedSystems?.[0]??'')}">${e(fact.label)}</option>`).join('')}</optgroup>`).join('');
  const common=`<input type="hidden" name="profileId" value="${profile.id}">${mode==='measurement'?renderAnatomyToggle():''}<label>Search measurements and sizes<input id="canonical-fact-search" type="search" autocomplete="off" aria-controls="canonical-fact-picker"></label><label>Fact<select id="canonical-fact-picker" name="canonicalFactId" required>${options}</select></label><p class="metadata">Category and label are set automatically from what you pick.</p>${mode==='measurement'?renderAnatomyDiscovery():''}`;
  let fields=mode==='measurement'?`${common}<h3 class="record-entry-heading">Record this measurement</h3><div class="form-row"><label>Recorded value<input name="value" type="number" step="any" required></label><label>Recorded unit<select id="canonical-choice" name="unit" required></select></label></div><label>Measured on<input name="measuredAt" type="date" value="${today()}"></label>`:mode==='standard_size'?`${common}<div class="form-row"><label>Recorded sizing system<select id="canonical-choice" name="sizingSystem" required></select></label><label>Recorded size<input name="sizeValue" required></label></div><label>Recorded on<input name="recordedAt" type="date" value="${today()}"></label>`:`${common}<label>Brand<input name="brand" required></label><label>Product name<input name="productName" required></label><label>Product line <span>optional</span><input name="productLine"></label><div class="form-row"><label>Recorded sizing system<select id="canonical-choice" name="sizingSystem" required></select></label><label>Recorded size<input name="sizeValue" required></label></div><label>Recorded on<input name="recordedAt" type="date" value="${today()}"></label>`;
  fields+=`<label>Source name <span>optional</span><input name="sourceName"></label><label>${mode==='brand_fit'?'Fit notes':'Notes'} <span>optional</span><textarea name="${mode==='brand_fit'?'fitNotes':'notes'}"></textarea></label>`;
  if(mode==='measurement')fields+=renderCreationGuidance();
  const custom=`<details class="custom-fact-path"><summary>Create custom fact</summary><p class="metadata">Custom facts may not support every conversion or discovery convenience. Unsupported conversions are never fabricated.</p><label><input type="checkbox" name="custom" value="yes"> Use custom fields</label><label>Custom label<input name="customLabel"></label><label>Custom category<select name="customCategory">${categoryOptions('')}</select></label><label>Custom measurement type or size context<input name="customContext"></label><label>Custom unit or sizing system<input name="customUnitOrSystem"></label></details>`;
  return `<section class="form-card form-panel" tabindex="-1" id="record-form-panel"><p class="eyebrow">Owner · ${e(profile.displayName)}</p><h2>Choose a fact</h2><p>This adds a record, not a recommendation.</p><form id="record-form" class="stacked-form">${fields}${custom}<div class="button-row"><button class="primary">Review and save</button><button type="button" class="quiet" id="cancel-record-form">Cancel</button></div></form></section>`;
}
const toolLabels:Record<GuidanceTool,string>={soft_tape:'Soft measuring tape',rigid_ruler:'Rigid ruler',stadiometer:'Stadiometer or vertical height measure',scales:'Level weighing scales',calipers:'Calipers',foot_measuring_device:'Foot-measuring device or rigid ruler',ring_sizer:'Ring sizer',other:'Suitable measuring tool'};
const assistanceLabels:Record<GuidanceAssistance,string>={self:'Suitable for self-measurement',assisted:'Easier and more consistent with another person',either:'Can be measured alone or with help',professional_preferred:'Professional help is preferred when available'};
export function renderGuidanceContent(guidance:MeasurementGuidance,heading=true,canonicalFactId?:string):string{return `<section class="measurement-guidance">${heading?'<h3>How to measure</h3>':''}${renderAnatomyIllustration(canonicalFactId)}<div class="guidance-critical"><div><h4>Where</h4><p>${e(guidance.location)}</p></div><div><h4>Method</h4><ol>${guidance.method.map((step)=>`<li>${e(step)}</li>`).join('')}</ol></div></div><dl class="guidance-meta"><div><dt>You will need</dt><dd>${e(toolLabels[guidance.tool])}</dd></div><div><dt>Assistance</dt><dd>${e(assistanceLabels[guidance.assistance])}</dd></div></dl><details class="guidance-secondary"><summary>Before measuring and common mistakes</summary>${guidance.preparation?.length?`<h4>Before measuring</h4><ul>${guidance.preparation.map((item)=>`<li>${e(item)}</li>`).join('')}</ul>`:''}${guidance.posture?`<p><strong>Posture:</strong> ${e(guidance.posture)}</p>`:''}${guidance.clothing?`<p><strong>Clothing:</strong> ${e(guidance.clothing)}</p>`:''}${guidance.commonErrors?.length?`<h4>Avoid</h4><ul>${guidance.commonErrors.map((item)=>`<li>${e(item)}</li>`).join('')}</ul>`:''}</details></section>`;}
function renderSavedGuidance(id:string|undefined):string{const guidance=measurementGuidanceFor(id);return guidance?`<details class="measurement-guidance-disclosure"><summary>Measurement guidance</summary>${renderGuidanceContent(guidance,true,id)}</details>`:`<details class="measurement-guidance-disclosure"><summary>Measurement guidance</summary><p class="metadata">This custom or legacy fact does not have standardised Sigma measurement guidance.</p></details>`;}
function renderCreationGuidance():string{return `<div id="creation-guidance" aria-live="polite">${canonicalFactsFor('measurement').filter((fact)=>fact.guidance).map((fact,index)=>`<details class="creation-guidance-disclosure" data-guidance-id="${fact.id}"${index?' hidden':''}><summary>How to measure</summary>${renderGuidanceContent(fact.guidance!,false,fact.id)}</details>`).join('')}</div>`;}
function renderConversions(results: ConversionResult[], provenance: string, heading: string): string { if (!results.length) return ''; const first = results[0]; return `<section class="conversion-block"><p class="eyebrow">${heading}</p><div class="conversion-values">${results.map((result) => `<span><strong>${typeof result.outputValue === 'number' ? formatConvertedValue(result.outputValue, result.outputSystem.includes('mm') ? 'mm' : result.outputSystem) : e(result.outputValue)} ${e(result.outputSystem)}</strong><small>${result.exact ? 'Exact conversion' : 'Approximate standard equivalent'}</small></span>`).join('')}</div><p class="metadata">${provenance}</p><details><summary>Conversion source & method</summary><p class="metadata">${e(first.source.authority)} · ${e(first.source.version)} · ${e(first.source.title)}</p>${first.note ? `<p class="metadata">${e(first.note)}</p>` : ''}</details></section>`; }
function unitOptions(dimension: Dimension): string { return unitsForDimension(dimension).map((unit) => `<option value="${unit.symbol}">${unit.symbol} · ${e(unit.label)}</option>`).join(''); }
function unitControl(dimension: Dimension | undefined, currentUnit: string): string { if (!dimension) return `<input name="unit" required value="${e(currentUnit)}">`; const known = unitsForDimension(dimension); const custom = known.some((unit) => unit.aliases.includes(currentUnit.toLowerCase())) ? '' : `<option value="${e(currentUnit)}" selected>${e(currentUnit)} · preserved recorded unit</option>`; return `<select name="unit" required>${custom}${known.map((unit) => `<option value="${unit.symbol}"${unit.aliases.includes(currentUnit.toLowerCase()) ? ' selected' : ''}>${unit.symbol} · ${e(unit.label)}</option>`).join('')}</select>`; }
const unsupported = () => `<p class="metadata conversion-unavailable">No supported deterministic conversion is available for this recorded fact.</p>`;
const none = (label: string) => `<div class="empty-inline"><p>No ${label} match this view. Add a recorded fact using the form.</p></div>`;
