import type { SigmaService } from '../../domain/service.js';
import type { PermissionKind } from '../../permissions/model.js';
import { permissionExplanations, PermissionDemoService } from '../../permissions/service.js';
import { sourceRegistry } from '../../sources/registry.js';
import type { ImportCandidate } from '../../sources/model.js';
import { escapeHtml as e, header } from './html.js';

const actions:Partial<Record<string,string>>={manual:'Go to Measurements',measurement_device:'Import measurement data',camera_assisted:'Measure with camera',body_scan:'Measure with camera',external_scan:'Choose scan file',smart_scale:'Connect measurement device'};
const decisionLabel=(value:string)=>value==='demo_granted'?'Simulated allow':value==='demo_denied'?'Simulated decline':'Not tried';
const fieldLabel=(value:string)=>value.split('.').at(-1)!.replaceAll('_',' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());
export function renderSources(service:SigmaService,permissions:PermissionDemoService,flow?:PermissionKind,candidates:readonly ImportCandidate[]=[] ,excluded=0,notice=''):string {
 const profiles=service.snapshot().profiles.filter(profile=>service.canManageProfile(profile.id));
 const explanation=flow?permissionExplanations[flow]:undefined;
 return header('Controlled acquisition','Sources','Manual entry is live. Every other source is a local demonstration or truthful future integration.')+
 (notice?`<section class="settings-card"><p class="eyebrow">Source status</p><p>${e(notice)}</p></section>`:'')+
 `<section class="settings-card"><p class="eyebrow">Import rule</p><h2>Nothing enters Sigma merely because a source exposes it.</h2><p>Unknown and unrelated fields fail closed. Accepted facts remain a preview until you confirm individual items.</p></section>`+
 (explanation?`<section class="settings-card permission-explanation"><p class="eyebrow">Local permission demonstration · no OS prompt</p><h2>${e(explanation.title)}</h2><p><strong>Requested access:</strong> ${e(explanation.requestedAccess)}</p><p><strong>Why:</strong> ${e(explanation.reason)}</p><p><strong>Will access:</strong> ${e(explanation.willAccess.join('; '))}</p><p><strong>Will not access:</strong> ${e(explanation.willNotAccess.join('; '))}</p><p><strong>Alternatives:</strong> ${e(explanation.alternatives.join('; '))}</p><p><strong>If declined:</strong> ${e(explanation.denialEffect)}</p><button data-permission-allow="${flow}">Simulate allow</button><button class="quiet" data-permission-decline="${flow}">Simulate decline</button></section>`:'')+
 (candidates.length?`<section class="settings-card"><p class="eyebrow">Filtered preview</p><h2>Choose individual candidates</h2><p>${excluded} unrelated fields were excluded by policy and are not selectable.</p>${profiles.length?`<label>Target profile<select id="import-target">${profiles.map(p=>`<option value="${p.id}">${e(p.displayName)}</option>`).join('')}</select></label>`:'<p>No profile managed by the acting adult is available.</p>'}${candidates.map((c,i)=>`<article class="record-card"><h3>${e(c.label)}</h3><p>${c.value} ${e(c.unitOrSystem)} · ${e(c.measuredAt)} · Local demo source · ${e(c.sourceDevice)} · confidence ${c.confidence} · ${c.derivation.kind}</p>${profiles.length?`<button data-import-candidate="${i}">Confirm this candidate</button>`:''}</article>`).join('')}</section>`:'')+
 `<section><p class="eyebrow">Available now</p>${renderSource(sourceRegistry.find(s=>s.id==='manual')!,permissions)}</section><section><p class="eyebrow">Local demonstration</p><p>No external device or service is contacted.</p>${renderSource(sourceRegistry.find(s=>s.id==='measurement_device')!,permissions)}</section><section><p class="eyebrow">Future integrations</p><p>These compact previews are not connected or usable.</p><div class="future-source-grid">${sourceRegistry.filter(s=>!['manual','measurement_device'].includes(s.id)).map(source=>renderSource(source,permissions)).join('')}</div></section>`;
}
function renderSource(source:(typeof sourceRegistry)[number],permissions:PermissionDemoService):string{return `<article class="settings-card source-card"><p class="eyebrow">${source.availability==='live'?'Live':source.availability==='demo'?'Local demo':'Future'}</p><h2>${e(source.label)}</h2><p>${e(source.description)}</p><p><strong>May provide:</strong> ${source.allowedExternalFields.length?source.allowedExternalFields.map(fieldLabel).map(e).join(', '):'User-entered measurements, sizes and fit facts'}</p><p><strong>Will not provide:</strong> ${e(source.excludedDataExamples.join(', '))}</p>${source.requiredPermission?`<p><strong>Demo state:</strong> ${decisionLabel(permissions.decision(source.requiredPermission))}</p>`:''}${actions[source.id]?`<button data-source-action="${source.id}"${source.id==='manual'?' data-route="measurements"':''}>${actions[source.id]}</button>`:'<p class="metadata">Not implemented.</p>'}</article>`;}
