import type { SigmaService } from '../../domain/service.js';
import type { PermissionKind } from '../../permissions/model.js';
import { permissionExplanations, PermissionDemoService } from '../../permissions/service.js';
import { sourceRegistry } from '../../sources/registry.js';
import type { ImportCandidate } from '../../sources/model.js';
import { escapeHtml as e, header } from './html.js';

const actions:Partial<Record<string,string>>={manual:'Go to Records',measurement_device:'Preview demo import',apple_health:'Preview health-data permission',health_connect:'Preview health-data permission',camera_assisted:'Preview camera permission',body_scan:'Preview camera permission',external_scan:'Inspect planned scan import',smart_scale:'Preview nearby-device permission'};
const decisionLabel=(value:string)=>value==='demo_granted'?'Simulated allow':value==='demo_denied'?'Simulated decline':'Not tried';
const fieldLabel=(value:string)=>value.split('.').at(-1)!.replaceAll('_',' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());
export function renderSources(service:SigmaService,permissions:PermissionDemoService,flow?:PermissionKind,candidates:readonly ImportCandidate[]=[] ,excluded=0,notice=''):string {
 const profiles=service.snapshot().profiles.filter(profile=>service.canManageProfile(profile.id));
 const explanation=flow?permissionExplanations[flow]:undefined;
 return header('Add records','Sources','Add records yourself, or try the local demo import.')+
 (notice?`<section class="settings-card" id="source-status" tabindex="-1"><p class="eyebrow">Source status</p><p>${e(notice)}</p></section>`:'')+
 (explanation?`<section class="settings-card permission-explanation" id="permission-explanation" tabindex="-1"><p class="eyebrow">Local permission demonstration · no OS prompt</p><h2>${e(explanation.title)}</h2><p><strong>Requested access:</strong> ${e(explanation.requestedAccess)}</p><p><strong>Why:</strong> ${e(explanation.reason)}</p><p><strong>Will access:</strong> ${e(explanation.willAccess.join('; '))}</p><p><strong>Will not access:</strong> ${e(explanation.willNotAccess.join('; '))}</p><p><strong>Alternatives:</strong> ${e(explanation.alternatives.join('; '))}</p><p><strong>If declined:</strong> ${e(explanation.denialEffect)}</p><button class="primary" data-permission-allow="${flow}">Simulate allow</button><button class="quiet" data-permission-decline="${flow}">Simulate decline</button></section>`:'')+
 (candidates.length?`<section class="settings-card" id="import-candidates" tabindex="-1"><p class="eyebrow">Filtered preview</p><h2>Choose individual candidates</h2><p>${excluded} unrelated fields were excluded by policy and are not selectable.</p>${profiles.length?`<label>Target profile<select id="import-target">${profiles.map(p=>`<option value="${p.id}">${e(p.displayName)}</option>`).join('')}</select></label>`:'<p>You do not have a profile you can import into.</p>'}<div class="candidate-list">${candidates.map((c,i)=>`<article class="record-card import-candidate"><div class="candidate-value"><h3>${e(c.label)}</h3><strong>${c.value} ${e(c.unitOrSystem)}</strong></div><dl class="candidate-metadata"><div><dt>Recorded</dt><dd>${e(c.measuredAt)}</dd></div><div><dt>Source</dt><dd>Local demo source</dd></div><div><dt>Device</dt><dd>${e(c.sourceDevice||'Not provided')}</dd></div><div><dt>Confidence</dt><dd>${c.confidence===undefined?'Not provided':`${Math.round(c.confidence*100)}%`}</dd></div><div><dt>Method</dt><dd>${c.derivation.kind==='direct'?'Direct':'Derived'}</dd></div></dl>${profiles.length?`<button class="primary" data-import-candidate="${i}">Confirm this candidate</button>`:''}</article>`).join('')}</div></section>`:'')+
 `<section><div class="section-heading"><h2>Manual entry</h2></div>${renderSource(sourceRegistry.find(s=>s.id==='manual')!,permissions)}</section><section><div class="section-heading"><h2>Measurement and sizing device demo</h2><span>No external service contacted</span></div>${renderSource(sourceRegistry.find(s=>s.id==='measurement_device')!,permissions)}</section><details class="settings-card source-policy"><summary>How imports are filtered</summary><p>Unknown or unrelated fields are dropped automatically. Nothing is added until you confirm each item.</p></details><details class="settings-card future-integrations"><summary>Future integrations (${sourceRegistry.filter(s=>!['manual','measurement_device'].includes(s.id)).length})</summary><p>These are previews only — nothing here is connected yet.</p><div class="future-source-grid">${sourceRegistry.filter(s=>!['manual','measurement_device'].includes(s.id)).map(source=>renderSource(source,permissions,true)).join('')}</div></details>`;
}
function renderSource(source:(typeof sourceRegistry)[number],permissions:PermissionDemoService,compact=false):string{return `<article class="${compact?'future-source-item':'settings-card source-card'}"><div class="source-heading"><div><p class="eyebrow">${source.availability==='live'?'Live':source.availability==='demo'?'Local demo':'Future'}</p><h2>${e(source.label)}</h2></div>${compact?'<span class="status-badge">Future</span>':''}</div><p>${e(source.description)}</p>${compact?'':`<details><summary>Data boundaries</summary><p><strong>May provide:</strong> ${source.allowedExternalFields.length?source.allowedExternalFields.map(fieldLabel).map(e).join(', '):'User-entered measurements, sizes and Brand & product facts'}</p><p><strong>Will not provide:</strong> ${e(source.excludedDataExamples.join(', '))}</p></details>`}${source.requiredPermission&&!compact?`<p class="metadata">Demo state: ${decisionLabel(permissions.decision(source.requiredPermission))}</p>`:''}${actions[source.id]?`<button class="${compact?'secondary':'primary'}" data-source-action="${source.id}"${source.id==='manual'?' data-route="measurements"':''}>${actions[source.id]}</button>`:compact?'<span class="metadata">View planned capability</span>':'<p class="metadata">Not implemented.</p>'}</article>`;}
