import type { SourceDefinition } from './model.js';
const excluded=['Heart rate','Sleep','Steps','GPS','Workouts','Blood oxygen','Diagnoses','Medication'];
export const sourceRegistry:readonly SourceDefinition[] = [
 {id:'manual',label:'Manual entry',description:'Enter a measurement or size yourself.',availability:'live',acquisitionMethod:'manual',supportedRecordKinds:['measurement','standard_size','brand_fit'],allowedExternalFields:[],excludedDataExamples:excluded},
 {id:'apple_health',label:'Apple Health',description:'Future allowlisted health-platform import.',availability:'future',acquisitionMethod:'imported_health_platform',requiredPermission:'health_data',supportedRecordKinds:['measurement'],allowedExternalFields:['body.height','body.weight'],excludedDataExamples:excluded},
 {id:'health_connect',label:'Android Health Connect',description:'Future allowlisted health-platform import.',availability:'future',acquisitionMethod:'imported_health_platform',requiredPermission:'health_data',supportedRecordKinds:['measurement'],allowedExternalFields:['body.height','body.weight'],excludedDataExamples:excluded},
 {id:'smart_scale',label:'Planned smart scale',description:'Future weight-only nearby-device preview.',availability:'future',acquisitionMethod:'imported_device',requiredPermission:'nearby_devices',supportedRecordKinds:['measurement'],allowedExternalFields:['body.weight'],excludedDataExamples:excluded},
 {id:'measurement_device',label:'Sigma demo measurement device',description:'Local measurement and sizing import demonstration; no external service is contacted.',availability:'demo',acquisitionMethod:'imported_device',requiredPermission:'health_data',supportedRecordKinds:['measurement','standard_size'],allowedExternalFields:['body.height','body.weight','body.waist_circumference','foot.length','size.shoe','size.ring'],excludedDataExamples:excluded},
 {id:'camera_assisted',label:'Camera-assisted measurement',description:'Future focused capture of one measurement; no capture or analysis occurs.',availability:'future',acquisitionMethod:'camera_assisted',requiredPermission:'camera',supportedRecordKinds:['measurement'],allowedExternalFields:['body.waist_circumference'],excludedDataExamples:excluded},
 {id:'body_scan',label:'Full body scan',description:'Future multi-measurement derived acquisition.',availability:'future',acquisitionMethod:'body_scan',requiredPermission:'camera',supportedRecordKinds:['measurement'],allowedExternalFields:['scan.chest_circumference'],excludedDataExamples:excluded},
 {id:'external_scan',label:'External scan import',description:'Future deliberate file selection; no parser exists.',availability:'future',acquisitionMethod:'body_scan',requiredPermission:'files',supportedRecordKinds:['measurement'],allowedExternalFields:['scan.chest_circumference'],excludedDataExamples:excluded},
 {id:'third_party_scanner',label:'Third-party scanner',description:'Future explicit scanner integration.',availability:'future',acquisitionMethod:'third_party_service',supportedRecordKinds:['measurement'],allowedExternalFields:['scan.chest_circumference'],excludedDataExamples:excluded},
];
